name: Teh-Urn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build -c release
    - name: Publish Commander
      run: dotnet nuget push "Commander/bin/Release/Commander.1.0.0.nupkg" --source "github"
    
    
